import React from 'react'
import ratingIcon from "@/asset/Icons/rating.svg";
import check3 from "@/asset/Icons/check3.svg";
import check4 from "@/asset/Icons/check4.svg";
import doctorList2 from "@/asset/Icons/doctorList2.svg";
import hospital7 from "@/asset/Icons/hospital7.svg";
import setup from "@/asset/Icons/setup.svg";

import Banner2 from '@/components/Banner2';


import doctor8 from "@/asset/Images/doctor8.png"
import circle1 from "@/asset/Images/circle1.png"
import header3 from "@/asset/Images/header3.png"
import header6 from "@/asset/Images/header6.png"


export default function page() {

const data1=[
  {
    mainText: " 1M+ Monthly Rx",
    subText: "Monthly Prescriptions generated by doctors using Welldone "
  },
  {
    mainText: " 1.5x Efficiency",
    subText: " Increase in Efficiency for doctors, saving time and improving care"
  },
  {
    mainText: "2x Follow-ups ",
    subText: " More Follow-ups, boosting patient engagement and retention"
  },
]


const boxStyle = {
  boxShadow: "0px 0px 6px 2px #01549A40",
  background: "linear-gradient(270.3deg, #54B1FF 1.26%, #48ABFF 22.82%, #01549A 99.74%)"
};
const boxStyle2 = {
  background: 'linear-gradient(305.37deg, #F4FAFF 0.29%, #CAE7FF 99.71%)',
  boxShadow: '0px 0px 4px 0px #01549A40'
};


const SmallBox =({image,heading,subText})=>(
  <div className='  asm:min-w-[120px] w-[96%] ssm:w-[90%] asm:w-[70%] msm:w-[40%] sm:w-[50%] max-w-[350px]  msm:max-w-[400px]   overflow-hidden   space-y-2' >
<img src={image?.src} className='block mx-auto w-[55px] sm:w-[65px] lsm:w-auto' alt="load..."  />
<p className=' text-xl   msm:text-sm sm:text-base lsm:text-xl xl:text-2xl  text-wrap sm:text-nowrap text-primary font-medium text-center leading-tight'>{heading}</p>
<p className='leading-tight text-center  text:sm msm:text-[11px]   sm:text-sm lsm:text-base max-msm:leading-tight'>{subText}</p>
  </div>
)    


  return (
    <div className="w-full  relative max-w-[1600px] space-y-20  mx-auto s    pt-[1px]    ">


{/* -----------------main header----------------- */}
<div 
style={{ background: 'linear-gradient(95.92deg, #F7FBFF 0%, #DEF0FF 95.3%)' }}
className="w-full max-md:pb-10 flex  flex-col md:flex-row  relative ">
  <div className=" max-md:order-2 md:absolute md:top-16 -mt-6 msm:-mt-8  md:-mt-0  md:pt-16 xl:pt-24 2xl:pt-36 px-3 msm:pl-5 xl:pl-12  lsm:left-6 md:transform md:-translate-y-1/2 md:z-10   ">

    <div className="text-primary leading-tight">
      <p className=" text-base  asm:text-xl 2xl:text-2xl font-bold">Become a</p>
      <p className=" text-[19px]  asm:text-[26px] msm:text-[28px] md:text-[26px]  lg:text-[36px] 2xl:text-[38px] font-bold">Welldone Health practitioner</p>
      <p className=" mt-1 text-[20px] ssm:text-[22px]  asm:text-[28px]  msm:text-[32px] md::text-[28px]  lsm:text-[30px] lg:text-[36px] xl:text-[42px] 2xl:text-[44px]  sm:whitespace-nowrap">Get 6-month subscription at just ₹2999*</p>
    </div>


{/* -----flex-------- */}
    <div className="font-bold rounded-tl-[3px]  rounded-bl-[25px] hidden border-transparent overflow-hidden bg-primary items-center ">
      <div style={{ boxShadow: '0px 0px 4px 0px #00000040' }} className="text-primary bg-secondary p-3 rounded-tr-[25px]  border-transparent">15 <br /> DAYS</div>
      <div className="text-white text-center leading-tight bg-primary px-5 py-3 overflow-hidden rounded-tr-[25px]  rounded-br-[3px] border-transparent ">Money Back <br/> Guarantee*</div>
    </div>




  </div>

  <div className="max-md:order-1  w-[90%] md:w-[60%]  max-md:mx-auto md:ml-auto ">
    <img src={header6?.src} className="w-full " alt="load..." />
  </div>
</div>





<div className="w-full   space-y-20 px-1 asm:px-3  lg:px-[2rem] overflow-hidden">

{/* -------------1st part---------flex-------------------------- */}
<div style={{ boxShadow: "0px 0px 4px 0px #01549A40" }} className="w-full xl:w-[90%] mx-auto px-3 asm:px-5   xl:px-10 pt-6 pb-10   border-[1px] border-[#DADADA]   rounded-3xl flex flex-col justify-center items-center gap-y-6">
 <p className='font-medium text-[24px] asm:text-[26px]  msm:text-3xl'>Why Use <span className='text-primary'>Welldone Health?</span></p>
 <button   type="button"  className="text-base msm:text-lg px-10  py-2 rounded-[30px]  font-semibold  bg-primary text-white"   >  Register Here     </button>
<p>Discover how Welldone Health makes healthcare smarter, faster, and more efficient!</p>

<div className="flex flex-col md:flex-row   md:justify-between gap-y-6 gap-x-6 lg:gap-x-8 2xl:gap-x-12 ">
  {data1.map((item,index)=><div key={index} className='flex-1 xl:w-[330px] px-6 py-5 rounded-xl bg-[#EBF6FF] space-y-1'>
<p className=' text-[22px]   lsm:text-[25px] xl:text-[32px] font-medium text-primary' >{item?.mainText}</p>
<p className='w-full max-ams:text-sm' >{item?.subText}</p>
  </div>)}

</div>

</div>





{/* -------------------2nd part------flex--------------- */}
<div  className="w-full  px-2  flex flex-col md:flex-row  md:justify-center items-center  ">




{/* --------------1st card----------- */}
<div style={boxStyle} className=" max-msm:mr-auto z-20  w-[95%]  asm:w-[90%] max-msm:max-w-[380px] msm:w-[380px] lg:w-[420px] px-5 lg:px-10 py-5 lg:py-8 rounded-3xl text-white">

  {/* -------1st------ */}
 <div className="pb-4 border-b-[1px] border-white space-y-2">
 <div className="flex gap-x-3 text-lg font-bold "><img src={ratingIcon?.src} className='' alt="load..." />Standard Plan</div>
 <div className="text-[26px] msm:text-3xl lg:text-[34px] flex gap-x-5">
  <p className='text-[#AAD5FA] line-through '>₹6900.00</p>
  <p className='font-bold'>₹2999*</p>
 </div>
 </div>

 <div className=" my-4 lg:my-6 space-y-3">
  {[" 6-month subscription for only ₹2999*!","15-day money-back promise! ","Zero setup fee","Zero hidden charges ","Unlimited access to Doctors and your staff "].map((item,index)=><div key={index} className="flex gap-x-3 items-center text-xs msm:text-sm  lsm:text-base"><img src={check3?.src} className='' alt="load..."  /> {item}  </div>)}
 </div>

<div className="mt-4 lg:mt-6 mb-3 space-y-2">
  <p className='text-xs lsm:text-sm'>*T&C Apply</p>
  <button   type="button"  className="text-sm asm:text-base msm:text-lg px-10  py-2 rounded-[30px]  font-semibold  bg-white text-primary"   > Get started for free   </button>
</div>

</div>






{/* ------------------2nd card----------------- */}
<div style={boxStyle2} className=" max-msm:ml-auto msm:-mr-28 md:-mr-0 -mt-14 md:-mt-0  pt-16  max-lg:-ml-2 w-[95%]  asm:w-[90%] max-msm:max-w-[380px]  msm:w-[360px] lsm:w-auto px-4  asm:pl-6 asm:pr-6 lsm:pr-10  md:pt-[12.8px] lg:pt-4 pb-[26px] lg:pb-6 max-md:rounded-3xl md:rounded-r-3xl max-md:border-[1px] md:border-y-[1px]  md:border-r-[1px]  border-[#54B1FF]">
{/* -----------1st------- */}
<div className="pb-2 border-b-[1px] border-[#5A5D62] space-y-1">
 <p className=" text-lg font-bold ">Platform fees</p>
 <div className="text-[26px] msm:text-3xl lg:text-[34px] flex gap-x-6 font-bold ">
  <p className='text-[#01549A47] line-through '>5.95%</p>
  <p className='text-primary'>Free*</p>
 </div>
 </div>
{/* -------2nd-------- */}
 <p className='mt-3 mb-2 lsm:mb-3 text-wrap text-[13px] msm:text-[15px] lsm:text-base lsm:text-nowrap'>0% Platform fees on Online Appointment Bookings!</p>

    <div className="space-y-2 asm:space-y-3">
      <p className='font-bold text-lg lsm:text-[20px]'>Benefits-</p>
      {["Keep 100% of your earnings","Increase patient bookings with no extra cost","Seamless and fast booking process "," Secure and transparent payment system ","Expand your reach with online visibility "].map((item,index)=><div key={index} className="flex gap-x-3 items-center text-xs msm:text-sm  lsm:text-base"><img src={check4?.src} className='' alt="load..."  /> {item}  </div>)}
    </div>



</div>


</div>




{/* --------------------3rd part---------------------- */}
<div className="  w-full xl:w-[95%] px-3  md:px-6  lg:px-14 pt-3 sm:pt-6 pb-10 mx-auto  border-[1px] border-[#DADADA] rounded-3xl  space-y-8  ">
    <p className='font-bold   text-[22px]  asm:text-[24px] msm:text-[28px]  md:text-[36px] text-center leading-tight'>You are just <span className='text-primary'>three steps away...</span></p>


<div className="w-full flex flex-col msm:flex-row max-msm:items-center  justify-center sm:justify-between gap-y-3  gap-x-2 md:gap-x-5">

<SmallBox image={hospital7} heading="List your Clinic/Hospital" subText="Help patients find your clinic or hospital by creating a listing on Welldone Health" /> 
<div className="flex items-center overflow-hidden">
<p className='font-medium text-nowrap max-msm:rotate-90 '>------------------  </p>
</div>
<SmallBox image={setup} heading="Setup" subText="Start receiving patients online and manage appointments effortlessly through our partner app, web dashboard, and more!" /> 
<div className="flex items-center  overflow-hidden  ">
<p className='font-medium text-nowrap max-msm:rotate-90 '>------------------</p>
</div>
<SmallBox image={doctorList2} heading="List Doctors" subText="Register your doctors for online appointments and deliver treatment to millions of patients with ease!" /> 

</div>


{/* ---------------4th part--------------- */}

<div className="max-msm:pt-8 w-full flexCenter">
<button type="button"  className='text-[15px]  sm:text-lg px-6 md:px-10  py-2 rounded-[30px]  font-semibold  bg-primary text-white'  >Start getting patients</button>
</div>
</div>






<div className=" sm:pt-10 lg:pt-16 xl:pt-36">
  <Banner2 />
</div>


</div>


        </div>
  )
}
